# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SicrediChallenge' do
  
  pod 'UIFlow', '~> 1.0'
  pod 'RestService', '~> 1.0'
  pod 'OHHTTPStubs/Swift', '9.0.0', :configuration => 'Debug'
  pod 'Kingfisher', '5.7.1'


  target 'SicrediChallengeTests' do
    inherit! :search_paths
    pod 'Nimble', '8.0.5'
    pod 'Quick',  '2.2.0'
  end

  target 'SicrediChallengeUITests' do
    # Pods for testing
  end

end
